version: '3.9'
services:
  db:
    image: postgres:15
    container_name: schoolverse_db_dev
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-schoolverse}
    ports:
      - "5432:5432"
    volumes:
      - db_data_dev:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7
    container_name: schoolverse_redis_dev
    ports:
      - "6379:6379"
    volumes:
      - redis_data_dev:/data

  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: schoolverse_app_dev
    env_file:
      - .env.docker.dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - db
      - redis
    command: npm run dev

  rt:
    image: node:20-alpine
    container_name: schoolverse_rt_dev
    working_dir: /app
    environment:
      - RT_PORT=3001
    ports:
      - "3001:3001"
    volumes:
      - .:/app
    command: sh -c "npm ci --no-audit --no-fund --legacy-peer-deps && node server/index.js"

volumes:
  db_data_dev:
  redis_data_dev:
